<?php return array(
    'root' => array(
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '2a23f0ef34dc6823e41b3137673d9700ad4e3f4f',
        'name' => 'ikechukwukalu/clamavfileupload',
        'dev' => true,
    ),
    'versions' => array(
        'brick/math' => array(
            'pretty_version' => 'v0.11.x-dev',
            'version' => '0.11.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'reference' => '8d60a347dd96c2c748f8993300a27d079a53144a',
            'dev_requirement' => false,
        ),
        'cordoval/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'davedevelopment/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'dflydev/dot-access-data' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dflydev/dot-access-data',
            'aliases' => array(
                0 => '3.x-dev',
            ),
            'reference' => 'f41715465d65213d644d3141a6a93081be5d3549',
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.1.x-dev',
            'version' => '2.1.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'reference' => 'bf265da9f831e46e646c7a01b59ee8a33f8c0365',
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '3.0.x-dev',
            'version' => '3.0.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'reference' => '84a527db05647743d50373e0ec53a152f2cde568',
            'dev_requirement' => false,
        ),
        'dragonmantank/cron-expression' => array(
            'pretty_version' => 'v3.3.2',
            'version' => '3.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dragonmantank/cron-expression',
            'aliases' => array(),
            'reference' => '782ca5968ab8b954773518e9e49a6f892a34b2a8',
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '4.x-dev',
            'version' => '4.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'reference' => '3a85486b709bc384dae8eb78fb2eec649bdb64ff',
            'dev_requirement' => false,
        ),
        'fakerphp/faker' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fakerphp/faker',
            'aliases' => array(
                0 => '1.21.x-dev',
            ),
            'reference' => 'ec2cb4993af55ed9924ad6806121cd062fbb04c9',
            'dev_requirement' => true,
        ),
        'fruitcake/php-cors' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fruitcake/php-cors',
            'aliases' => array(
                0 => '1.2.x-dev',
            ),
            'reference' => 'bb96f0246364ea36d4d22364a39023a7e2974fc8',
            'dev_requirement' => false,
        ),
        'graham-campbell/result-type' => array(
            'pretty_version' => '1.1.x-dev',
            'version' => '1.1.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../graham-campbell/result-type',
            'aliases' => array(),
            'reference' => '821e73872c8eec935700049e46e009382a2efaaf',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(
                0 => '2.4.x-dev',
            ),
            'reference' => '58d0734481de3fbc62f3d13da4d991e051521282',
            'dev_requirement' => true,
        ),
        'guzzlehttp/uri-template' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/uri-template',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'reference' => 'b945d74a55a25a949158444f09ec0d3c120d69e2',
            'dev_requirement' => false,
        ),
        'hamcrest/hamcrest-php' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../hamcrest/hamcrest-php',
            'aliases' => array(
                0 => '2.1.x-dev',
            ),
            'reference' => 'd34238d1651eb62fc39ab4efe26df74dc293ebbb',
            'dev_requirement' => true,
        ),
        'ikechukwukalu/clamavfileupload' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '2a23f0ef34dc6823e41b3137673d9700ad4e3f4f',
            'dev_requirement' => false,
        ),
        'illuminate/auth' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/broadcasting' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/bus' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/collections' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/conditionable' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/config' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/container' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/cookie' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/database' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/encryption' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/events' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/hashing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/http' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/log' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/macroable' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/mail' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/notifications' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/pagination' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/pipeline' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/process' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/queue' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/redis' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/routing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/session' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/support' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/testing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/translation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/validation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'illuminate/view' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.x-dev',
            ),
        ),
        'kodova/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'laravel/framework' => array(
            'pretty_version' => '10.x-dev',
            'version' => '10.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/framework',
            'aliases' => array(),
            'reference' => '39f28e828de7f4be24cc4a21353d6ef2a6f65ce3',
            'dev_requirement' => false,
        ),
        'laravel/serializable-closure' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/serializable-closure',
            'aliases' => array(
                0 => '1.x-dev',
            ),
            'reference' => '8746f27d79cb4412907b3e42f7d6a5e0630c0463',
            'dev_requirement' => false,
        ),
        'league/commonmark' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/commonmark',
            'aliases' => array(
                0 => '2.4.x-dev',
            ),
            'reference' => '843213d315d4a5aa3e827a873abce65dbb21a3e4',
            'dev_requirement' => false,
        ),
        'league/config' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/config',
            'aliases' => array(
                0 => '1.2.x-dev',
            ),
            'reference' => 'fbb4c4ab01d6d14a6db46923671bb1c2ee5b6691',
            'dev_requirement' => false,
        ),
        'league/flysystem' => array(
            'pretty_version' => '3.x-dev',
            'version' => '3.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/flysystem',
            'aliases' => array(),
            'reference' => '81e87e74dd5213795c7846d65089712d2dda90ce',
            'dev_requirement' => false,
        ),
        'league/mime-type-detection' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/mime-type-detection',
            'aliases' => array(),
            'reference' => 'ff6248ea87a9f116e78edd6002e39e5128a0d4dd',
            'dev_requirement' => false,
        ),
        'mockery/mockery' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mockery/mockery',
            'aliases' => array(),
            'reference' => 'e92dcc83d5a51851baf5f5591d32cb2b16e3684e',
            'dev_requirement' => true,
        ),
        'monolog/monolog' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(
                0 => '3.x-dev',
            ),
            'reference' => 'd3d495b742cacf9c0af87867bf87dab2fc591e68',
            'dev_requirement' => false,
        ),
        'mtdowling/cron-expression' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^1.0',
            ),
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'reference' => '14daed4296fae74d9e3201d2c4925d1acb7aa614',
            'dev_requirement' => true,
        ),
        'nesbot/carbon' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(
                0 => '2.x-dev',
            ),
            'reference' => '496712849902241f04902033b0441b269effe001',
            'dev_requirement' => false,
        ),
        'nette/schema' => array(
            'pretty_version' => 'v1.2.x-dev',
            'version' => '1.2.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/schema',
            'aliases' => array(),
            'reference' => 'b6b3f41ea96ebf082657d271d9b1bac6071d7d29',
            'dev_requirement' => false,
        ),
        'nette/utils' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/utils',
            'aliases' => array(
                0 => '4.0.x-dev',
            ),
            'reference' => '3678b205594039535be40927a3cade2743954d47',
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => '4.x-dev',
            'version' => '4.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'reference' => '570e980a201d8ed0236b0a62ddf2c9cbb2034039',
            'dev_requirement' => true,
        ),
        'nunomaduro/termwind' => array(
            'pretty_version' => 'v1.15.1',
            'version' => '1.15.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nunomaduro/termwind',
            'aliases' => array(),
            'reference' => '8ab0b32c8caa4a2e09700ea32925441385e4a5dc',
            'dev_requirement' => false,
        ),
        'orchestra/testbench' => array(
            'pretty_version' => '8.x-dev',
            'version' => '8.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../orchestra/testbench',
            'aliases' => array(),
            'reference' => 'd01c35f246942d1fbb30d6747e0a04351228d295',
            'dev_requirement' => true,
        ),
        'orchestra/testbench-core' => array(
            'pretty_version' => '8.x-dev',
            'version' => '8.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../orchestra/testbench-core',
            'aliases' => array(),
            'reference' => 'd89db1462a3aa3658cf584f30c41af6a190a450f',
            'dev_requirement' => true,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(
                0 => '2.0.x-dev',
            ),
            'reference' => '36d8a21e851a9512db2b086dc5ac2c61308f0138',
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'reference' => '4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
            'dev_requirement' => true,
        ),
        'phpoption/phpoption' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoption/phpoption',
            'aliases' => array(
                0 => '1.9.x-dev',
            ),
            'reference' => '00430c0532ae544fb1c81e45705b3d356bfc25d0',
            'dev_requirement' => false,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(
                0 => '10.0.x-dev',
            ),
            'reference' => '4baff6b46559d258fdb41a10a2f52634a4e3ec14',
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(
                0 => '4.0.x-dev',
            ),
            'reference' => 'b8f1a8d493a4cc4da1520b9484fd3e28bc9b2e6e',
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(
                0 => '4.0.x-dev',
            ),
            'reference' => '2ad867e3066e8699c270775bc20be47dddfe835a',
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(
                0 => '3.0.x-dev',
            ),
            'reference' => 'fe38a3a9729f510e76b721ccac5987febb378079',
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(
                0 => '6.0.x-dev',
            ),
            'reference' => '4a6736c64a31ff1d14dd85abd0635a4c8d622665',
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(
                0 => '10.1.x-dev',
            ),
            'reference' => '260fdf4420effafe52e6d9d6cdf18b11c7f19baa',
            'dev_requirement' => true,
        ),
        'pimple/pimple' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pimple/pimple',
            'aliases' => array(),
            'reference' => 'a94b3a4db7fb774b3d78dad2315ddc07629e1bed',
            'dev_requirement' => true,
        ),
        'predis/predis' => array(
            'pretty_version' => 'v2.x-dev',
            'version' => '2.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../predis/predis',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '26c625230fa5f9dc97e39cb61942530a223a93a5',
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(
                0 => '2.0.x-dev',
            ),
            'reference' => '90db7b9ac2a2c5b849fcb69dde58f3ae182c68f5',
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0',
            ),
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'reference' => 'e275e2d67d53964a3f13e056886ecd769edee021',
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'reference' => '5a4f141ac2e5bc35e615134f127e1833158d2944',
            'dev_requirement' => true,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'reference' => 'efd67d1dc14a7ef4fc4e518e7dee91c271d524e4',
            'dev_requirement' => true,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(
                0 => '3.x-dev',
            ),
            'reference' => 'fe5ea303b0887d5caefd3d431c3e61ad47037001',
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '3.0.0',
                1 => '1.0|2.0|3.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(
                0 => '3.0.x-dev',
            ),
            'reference' => '2d280c2aaa23a120f35d55cfde8581954a8e77fa',
            'dev_requirement' => false,
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0|3.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => true,
        ),
        'ramsey/collection' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/collection',
            'aliases' => array(),
            'reference' => 'a4b48764bfbb8f3a6a4d1aeb1a35bb5e9ecac4a5',
            'dev_requirement' => false,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '4.x-dev',
            'version' => '4.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'reference' => 'bf2bee216a4379eaf62162307d62bb7850405fec',
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.x-dev',
            ),
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(
                0 => '2.0.x-dev',
            ),
            'reference' => '3d770b40d03d11de194ea5dc2c6ab968713757ec',
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(
                0 => '2.0.x-dev',
            ),
            'reference' => '045d35827fd42bce6f1a0e93a6c210fad404477d',
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(
                0 => '3.0.x-dev',
            ),
            'reference' => '0db2debe4565311c15e24f4aba9811ed05a9e740',
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(
                0 => '5.0.x-dev',
            ),
            'reference' => '4917a070c3d384961e41a90089a9d3dc2653943a',
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(
                0 => '3.0.x-dev',
            ),
            'reference' => '8bc94f3b83459a5b02fdeb9e28231cdbe967528b',
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(
                0 => '5.0.x-dev',
            ),
            'reference' => 'a307691c89a40ea30bc2d161686347f69570f1d1',
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(
                0 => '6.0.x-dev',
            ),
            'reference' => 'dae2d289647dead0603a14a991b756107042a545',
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(
                0 => '5.0.x-dev',
            ),
            'reference' => '988f65481f95f3080d7b412d4fc863b7d09c36b2',
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(
                0 => '6.0.x-dev',
            ),
            'reference' => '54f2b8b4c9b2150967b7a4f88b1130e8b240e03e',
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(
                0 => '2.0.x-dev',
            ),
            'reference' => 'd72a64a56744b586665ab6b8348a87c17184e99c',
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(
                0 => '5.0.x-dev',
            ),
            'reference' => '1e0e798e8485c99d58dd48329d22492c4b823f0f',
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(
                0 => '3.0.x-dev',
            ),
            'reference' => '4195704e990175e04c38bbf953888b2a12a6e034',
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(
                0 => '5.0.x-dev',
            ),
            'reference' => 'b41261ae42526a240bd640fd8d99cd1f28adcbed',
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(
                0 => '4.0.x-dev',
            ),
            'reference' => 'e1c36e7d18f12a7b897baf491b939964ba0b25f6',
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(
                0 => '4.0.x-dev',
            ),
            'reference' => 'f1f99b098f6a487eb2a4b01784276a48bc1073de',
            'dev_requirement' => true,
        ),
        'spatie/backtrace' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/backtrace',
            'aliases' => array(),
            'reference' => '7b34fee6c1ad45f8ee0498d17cd8ea9a076402c1',
            'dev_requirement' => true,
        ),
        'spatie/laravel-ray' => array(
            'pretty_version' => '1.32.2',
            'version' => '1.32.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-ray',
            'aliases' => array(),
            'reference' => '0c28a8274ec261a2857b4318b6f934af98024395',
            'dev_requirement' => true,
        ),
        'spatie/macroable' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/macroable',
            'aliases' => array(),
            'reference' => 'ec2c320f932e730607aff8052c44183cf3ecb072',
            'dev_requirement' => true,
        ),
        'spatie/ray' => array(
            'pretty_version' => '1.36.2',
            'version' => '1.36.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/ray',
            'aliases' => array(),
            'reference' => '71dfde21900447ab37698fc07ff28b7f1e1822b8',
            'dev_requirement' => true,
        ),
        'symfony/console' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => '252806398836dde17db75a75566d1f291e4648b0',
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'reference' => 'efc074765e98f4c25a52299d0148ac798cb9f98e',
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(
                0 => '3.3.x-dev',
            ),
            'reference' => '1ee04c65529dea5d8744774d474e7cbd2f1206d3',
            'dev_requirement' => false,
        ),
        'symfony/error-handler' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/error-handler',
            'aliases' => array(),
            'reference' => '1e4c2b6371a3507f5ba14018ee145d58e7aa2e8f',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'reference' => 'c58ec8623b8cbb3739fbaab5bf972df3f68ef312',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(
                0 => '3.3.x-dev',
            ),
            'reference' => '0782b0b52a737a05b4383d0df35a474303cabdae',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0|3.0',
            ),
        ),
        'symfony/finder' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'reference' => 'f5891f0383dc22a615ebd5848e87328d1efad0be',
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'reference' => '0bb5ab018fd4d9b76174696ee8770dd5e2e99d12',
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'reference' => 'e051bb5dfb8a4488d64da903ce0a6b560a3e8f6f',
            'dev_requirement' => false,
        ),
        'symfony/mailer' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mailer',
            'aliases' => array(),
            'reference' => 'da56c4e7f599f1e92fe78f5065bb8eb147bb0aa5',
            'dev_requirement' => false,
        ),
        'symfony/mime' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'reference' => 'd031788170c174a4fa0aa56e804080a32b0aefaa',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'reference' => 'ea208ce43cbb04af6867b4fdddb1bdbf84cc28cb',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'reference' => '6de50471469b8c9afc38164452ab2b6170ee71c1',
            'dev_requirement' => true,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'reference' => '875e90aeea2777b6f135677f618529449334a612',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'reference' => 'ecaafce9f77234a6a449d29e49267ba10499116d',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'reference' => '8c4ad05dd0120b6a53c1ca374dca2ad0a1c4ed92',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'reference' => 'f9c7affe77a00ae32ca127ca6833d034e6d33f25',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'reference' => '70f4aebd92afca2f865444d30a4d2151c13c3179',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'reference' => '6caa57379c4aec19c0a12a38b59b26487dcfe4b5',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php83' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php83',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'reference' => '4d30d60ba762ce6792e014576b57fa48ad5c5a68',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-uuid' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-uuid',
            'aliases' => array(
                0 => '1.28.x-dev',
            ),
            'reference' => '9c44518a5aff8da565c8a55dbe85d2769e6f630e',
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'reference' => '8d7df636e53698bf990ec0a22b67ec273aabf608',
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'reference' => 'ca5f274ab74ccaaf6d97b3284d0995592874e8e5',
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(
                0 => '3.3.x-dev',
            ),
            'reference' => 'aac98028c69df04ee77eb69b96b86ee51fbf4b75',
            'dev_requirement' => false,
        ),
        'symfony/stopwatch' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/stopwatch',
            'aliases' => array(),
            'reference' => 'f7fa451783b748e7b5942b9afe889b8df062e935',
            'dev_requirement' => true,
        ),
        'symfony/string' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'reference' => '6515bacc98212164f10db4371fa70ee7b8c70b80',
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'reference' => '1d123ac60b26c7facfaa0cd5fa311880e00cd755',
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(
                0 => '3.3.x-dev',
            ),
            'reference' => '68cce71402305a015f8c1589bfada1280dc64fe7',
            'dev_requirement' => false,
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.3|3.0',
            ),
        ),
        'symfony/uid' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/uid',
            'aliases' => array(),
            'reference' => '393bf72ac46cce9408a88e85e867ab512da9ccff',
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'reference' => '65479a220e49a6ae97df29a64a4b0966c644515b',
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => '6.3.x-dev',
            'version' => '6.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => '55071edc7115b1bfb15f286b4d6784a84ff09351',
            'dev_requirement' => true,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'reference' => '34a41e998c2183e22995f158c581e7b5e755ab9e',
            'dev_requirement' => true,
        ),
        'tijsverkoyen/css-to-inline-styles' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tijsverkoyen/css-to-inline-styles',
            'aliases' => array(
                0 => '2.2.x-dev',
            ),
            'reference' => 'c42125b83a4fa63b187fdf29f9c93cb7733da30c',
            'dev_requirement' => false,
        ),
        'vlucas/phpdotenv' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vlucas/phpdotenv',
            'aliases' => array(
                0 => '5.5.x-dev',
            ),
            'reference' => '1a7ea2afc49c3ee6d87061f5a233e3a035d0eae7',
            'dev_requirement' => false,
        ),
        'voku/portable-ascii' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../voku/portable-ascii',
            'aliases' => array(),
            'reference' => 'b56450eed252f6801410d810c8e1727224ae0743',
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'reference' => '11cb2199493b2f8a3b53e7f19068fc6aac760991',
            'dev_requirement' => false,
        ),
        'zbateson/mail-mime-parser' => array(
            'pretty_version' => '2.4.0',
            'version' => '2.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zbateson/mail-mime-parser',
            'aliases' => array(),
            'reference' => '20b3e48eb799537683780bc8782fbbe9bc25934a',
            'dev_requirement' => true,
        ),
        'zbateson/mb-wrapper' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zbateson/mb-wrapper',
            'aliases' => array(),
            'reference' => 'faf35dddfacfc5d4d5f9210143eafd7a7fe74334',
            'dev_requirement' => true,
        ),
        'zbateson/stream-decorators' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zbateson/stream-decorators',
            'aliases' => array(),
            'reference' => '7466ff45d249c86b96267a83cdae68365ae1787e',
            'dev_requirement' => true,
        ),
    ),
);
